require 'wee/components/wrapper_decoration'
require 'wee/components/form_decoration'
require 'wee/components/page_decoration'
require 'wee/components/messagebox'
require 'wee/components/component_dispatcher'
require 'wee/components/login_decoration'
require 'wee/components/pager'
